name: GitHub Actions Examen DIW

run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on:
  push:
    branches: ['main']
jobs:
  Examen1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.actor}}"
      - run: echo "${{ github.ref }} and your repository is ${{ github.repository }}."